#!/usr/bin/env python3

# Given two strings s and t which consist of only lowercase letters.
# String t is generated by random shuffling string s and then add one more letter
# at a random position.
#
# Find the letter that was added in t.
#
# Input:
# s = "abcd"
# t = "abcde"
#
# Output:
# e
#
# Explanation:
# 'e' is the letter that was added.

import sys

def findDifferentChar(s, t):
    i = 0
    for ch in s+t:
        i = i ^ ord(ch)
    return chr(i)

def findDifferentChar_2(s, t):
    i = 0
    for ch in s:
        i = i ^ ord(ch)
    for ch in t:
        i = i ^ ord(ch)
    return chr(i)

def main(arg):
    print(findDifferentChar(arg[0], arg[1]))
    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
